load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "line_log",
    srcs = ["src/line_log.cc"],
    hdrs = ["include/line_log/line_log.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "line_log_demo",
    srcs = ["src/demo.cc"],
    deps = [":line_log"],
)
